[http.middlewares]
  [http.middlewares.test-auth.basicAuth]
    users = [
      "<user>",
    ]
  [http.middlewares.secure-headers.headers]
    frameDeny = true
    contentTypeNosniff = true
    browserXssFilter = true
    sslRedirect = true
    stsSeconds = 31536000
    stsIncludeSubdomains = true
    stsPreload = true
    forceSTSHeader = true
    #contentSecurityPolicy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; connect-src 'self' wss:;"

