services:
  checkmk :
    image: checkmk/check-mk-raw:latest
    container_name: checkmk
    restart: always
    networks:
      - traefik_proxy
    #network_mode: host
    environment:
      - CMK_PASSWORD=${cmkpass}
      - TZ=America/Halifax

    volumes:
      - ${ROOT}/data:/omd/sites
      - /var/run/docker.sock:/var/run/docker.sock

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monitoring.rule=Host(`${URL}`)"
      - "traefik.http.routers.monitoring.entrypoints=websecure"
      - "traefik.http.routers.monitoring.tls.certresolver=<RESOLVER>"
      - "traefik.http.services.monitoring.loadbalancer.server.port=${PORT}"
      #- "traefik.http.services.monitoring.loadbalancer.server.url=https://127.0.0.1:${PORT}/cmk/"

networks:
  traefik_proxy:
    name: traefik_proxy
    external: true
  monitor_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.11.0
  
